apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gpu-support
- traefik
- home-assistant
- pihole
- ollama
- wyoming-whisper
- wyoming-piper

configMapGenerator:
- name: app-config
  files:
  - config.properties