apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-http-config
  namespace: home-assistant
data:
  http_config.yaml: |
    use_x_forwarded_for: true
    trusted_proxies:
      - 10.0.0.0/8      # Private Class A
      - 172.16.0.0/12   # Private Class B
      - 192.168.0.0/16  # Private Class C