apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/namespace.yaml
- resources/persistentvolume.yaml
- resources/persistentvolumeclaim.yaml
- resources/http-config.yaml
- resources/deployment.yaml
- resources/service.yaml
- resources/ingress.yaml