apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: wyoming-whisper
  labels:
    app: wyoming-whisper
spec:
  selector:
    app: wyoming-whisper
  ports:
  - name: wyoming
    port: 10300
    targetPort: 10300
    protocol: TCP
  type: ClusterIP