apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
  labels:
    app: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
  - name: dns-tcp
    port: 8053
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 8053
    targetPort: 53
    protocol: UDP
  - name: web
    port: 8080
    targetPort: 80
    protocol: TCP